"""Workspace management (multi-project manifests, init/list/check/compile)."""

from infra.workspace.lock import (
    LockError,
    LockInfo,
    WorkspaceLock,
    is_stale,
    lock_path,
    lock_status,
    read_lock,
)
from infra.workspace.manager import (
    DEFAULT_TARGET,
    TARGETS,
    TEMPLATES,
    WORKSPACE_FILE,
    WORKSPACE_VERSION,
    ProjectReport,
    ProjectSpec,
    Workspace,
    WorkspaceError,
    check_project,
    check_workspace,
    compile_project,
    find_workspace,
    init_workspace,
    load_workspace,
    project_status,
)

__all__ = [
    "DEFAULT_TARGET",
    "LockError",
    "LockInfo",
    "WorkspaceLock",
    "is_stale",
    "lock_path",
    "lock_status",
    "read_lock",
    "TARGETS",
    "TEMPLATES",
    "WORKSPACE_FILE",
    "WORKSPACE_VERSION",
    "ProjectReport",
    "ProjectSpec",
    "Workspace",
    "WorkspaceError",
    "check_project",
    "check_workspace",
    "compile_project",
    "find_workspace",
    "init_workspace",
    "load_workspace",
    "project_status",
]
