# ruff: noqa: E501
"""Base backend interface and shared helpers for the Infra compilers."""
# mypy: disable-error-code="no-untyped-def,no-untyped-call,no-any-return,index,attr-defined,type-arg,misc,union-attr,assignment"

from __future__ import annotations

import abc
import logging
import threading
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from ruamel.yaml import YAML

from infra.analyzer.symbols import SymbolTable
from infra.parser import ast_nodes as n

logger = logging.getLogger(__name__)

#: label applied to every generated resource
# NOTE: keep in sync with the literal labels in kubernetes.py; must be "infra-lang"
MANAGED_BY_LABEL = "app.kubernetes.io/managed-by: infra-lang"
# Legacy single-line header kept for any remaining callers; new code should use
# the `generated_header()` helper below so the version + source are included.
GENERATED_HEADER = "# Generated by Infra Language - DO NOT EDIT"


def generated_header(target: str = "kubernetes") -> str:
    """Return the AUTO-GENERATED header comment for a backend output.

    Includes the current version (from :mod:`infra.version`) and, when
    available, the source ``.infra`` file name (from the parser's per-thread
    current-file tracking). Falls back to ``source.infra`` when unknown.
    """
    from infra.parser.transformer import _CUR_FILE  # local to avoid cycles
    from infra.version import __version__

    src = getattr(_CUR_FILE, "value", None) or "source.infra"
    if src in ("<string>", "<prelude>", "source.infra"):
        src = "source.infra"
    return (
        f"# AUTO-GENERATED by infra-lang v{__version__} — do not edit manually.\n"
        f"# Source: {src}\n"
        f"# Regenerate: infra compile {src} --target {target}\n"
    )


class _ThreadLocalYAML:
    """Per-thread cached ruamel YAML emitter.

    ruamel's ``YAML`` is not thread-safe: a single shared instance mutated by
    concurrent ``dump()`` calls corrupts its internal emitter state. Recreating
    one per ``dump()`` is safe but expensive (large charts compile many
    resources). Caching a separate instance per thread gives us both safety and
    reuse: within one thread the emitter is reused across dumps, and different
    threads never share it.
    """

    def __init__(self) -> None:
        self._local = threading.local()

    def _make(self) -> YAML:
        y = YAML()
        y.default_flow_style = False
        y.sort_base_mapping_type = None  # preserves insertion order
        y.indent(mapping=2, sequence=4, offset=2)
        return y

    def get(self) -> YAML:
        y = getattr(self._local, "yaml", None)
        if y is None:
            y = self._make()
            self._local.yaml = y
        return y


_YAML_CACHE = _ThreadLocalYAML()


def _new_yaml() -> YAML:
    """Return a thread-safe ruamel YAML instance (reused within a thread)."""
    return _YAML_CACHE.get()


@dataclass
class CompileResult:
    """Output of a backend compile: a mapping of filename -> content."""

    files: Dict[str, str] = field(default_factory=dict)
    warnings: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_empty(self) -> bool:
        return len(self.files) == 0


@dataclass
class CompileContext:
    """Shared state passed to a backend during compilation."""

    program: n.Program
    symbol_table: Optional[SymbolTable] = None
    target_namespace: str = "default"
    environment: Optional[str] = None
    variables: Dict[str, Any] = field(default_factory=dict)
    debug: bool = False

    @classmethod
    def from_program(
        cls, program: n.Program, *, cli_vars: Optional[Dict[str, str]] = None, **kwargs: Any
    ) -> "CompileContext":
        """Build a context preloaded with top-level variable declarations.

        ``variables`` maps each name to its value node so that identifiers
        (e.g. ``image: myvar`` or template interpolation) resolve at
        compile time. ``cli_vars`` (from ``infra compile --var k=v``) override
        any variable of the same name.
        """
        ctx = cls(program=program, **kwargs)
        for stmt in program.statements:
            if isinstance(stmt, n.VariableDecl):
                ctx.variables[stmt.name] = stmt.value
        if cli_vars:
            for k, v in cli_vars.items():
                ctx.variables[k] = n.Literal(value=str(v))
        return ctx


class Backend(abc.ABC):
    """Abstract base class for all output backends."""

    @property
    @abc.abstractmethod
    def name(self) -> str: ...

    @property
    @abc.abstractmethod
    def description(self) -> str: ...

    @property
    @abc.abstractmethod
    def file_extension(self) -> str: ...

    supports_multi_file: bool = False

    def get_version(self) -> str:
        return "1.0"

    @abc.abstractmethod
    def compile(self, program: n.Program, **kwargs: Any) -> CompileResult: ...

    @abc.abstractmethod
    def compile_service(self, node: n.ServiceDef) -> str: ...

    @abc.abstractmethod
    def compile_database(self, node: n.DatabaseDef) -> str: ...


class BaseYAMLBackend:
    """Mixin providing YAML helpers shared by the YAML backends."""

    def _to_yaml(self, data: Any) -> str:
        import io

        buf = io.StringIO()
        _new_yaml().dump(data, buf)
        return buf.getvalue().rstrip("\n") + "\n"

    def _to_yaml_multi(self, docs: List[Any]) -> str:
        """Serialize several YAML documents in a single emitter pass.

        Uses ruamel's ``dump_all`` so all documents are written to one stream
        (separated by ``---``) with a single serializer/emitter pass. This is
        faster for large workloads than calling ``_to_yaml`` per resource, where
        the per-call serializer construction dominates.
        """
        if not docs:
            return ""
        import io

        buf = io.StringIO()
        _new_yaml().dump_all(docs, buf)
        return buf.getvalue().rstrip("\n") + "\n"

    def _clean_none(self, data: Any) -> Any:
        """Recursively remove keys whose value is None (or empty)."""
        if isinstance(data, dict):
            out = {}
            for k, v in data.items():
                v = self._clean_none(v)
                if v is None:
                    continue
                if isinstance(v, (dict, list)) and len(v) == 0:
                    continue
                out[k] = v
            return out
        if isinstance(data, list):
            return [self._clean_none(i) for i in data]
        return data

    def _snake_to_camel(self, name: str) -> str:
        parts = name.split("_")
        return parts[0] + "".join(p.title() for p in parts[1:])


# --------------------------------------------------------------------------- #
# Expression evaluation helpers
# --------------------------------------------------------------------------- #


def _is_ast_node(value: Any) -> bool:
    """True if *value* is an Infra AST node (needs recursive evaluation)."""
    return hasattr(value, "__class__") and getattr(
        value.__class__, "__module__", ""
    ).startswith("infra.parser")


def evaluate_expression(expr: Optional[n.Expression], context: CompileContext) -> Any:
    """Evaluate an AST expression to a Python value using the compile context.

    Supports literals, units, identifiers (resolved from context variables),
    template strings, binary operators, lists, maps and builtin calls. Unknown
    identifiers collapse to a ``${NAME}`` placeholder so backends emit a
    runtime-reference rather than crashing.
    """
    if expr is None:
        return None
    if isinstance(expr, n.Literal):
        return expr.value
    if isinstance(expr, n.Duration):
        return evaluate_duration(expr)
    if isinstance(expr, n.ResourceValue):
        return evaluate_resource(expr, "kubernetes")
    if isinstance(expr, n.Percentage):
        return f"{expr.value}%"
    if isinstance(expr, n.Identifier):
        if expr.name in context.variables:
            value = context.variables[expr.name]
            if _is_ast_node(value):
                return evaluate_expression(value, context)
            return value
        return f"${{{expr.name}}}"
    if isinstance(expr, n.TemplateString):
        parts = []
        for part in expr.parts:
            if isinstance(part, str):
                parts.append(part)
            elif isinstance(part, tuple) and part and part[0] == "expr":
                # raw expression source stored by the transformer
                from infra.parser import parse_expression  # local import

                sub = parse_expression(part[1])
                val = evaluate_expression(sub, context)
                parts.append(str(val) if val is not None else "")
            else:
                val = evaluate_expression(part, context)
                parts.append(str(val) if val is not None else "")
        return "".join(parts)
    if isinstance(expr, n.List):
        return [evaluate_expression(i, context) for i in expr.items]
    if isinstance(expr, n.Map):
        return {
            evaluate_expression(e.key, context): evaluate_expression(e.value, context)
            for e in expr.entries
        }
    if isinstance(expr, n.BinaryOp):
        left = evaluate_expression(expr.left, context)
        right = evaluate_expression(expr.right, context)
        op = expr.operator
        try:
            if op == "+":
                return left + right
            if op == "-":
                return left - right
            if op == "*":
                return left * right
            if op == "/":
                return left / right
            if op == "==":
                return left == right
            if op == "!=":
                return left != right
        except Exception as exc:  # noqa: BLE001 - lenient eval, log for diag
            logger.debug("binary eval failed (op=%s, l=%r, r=%r): %s",
                         getattr(expr, "operator", None), left, right, exc)
            return None
    if isinstance(expr, n.Call):
        return _eval_builtin(expr, context)
    return None


def _eval_builtin(expr: n.Call, context: CompileContext) -> Any:
    callee = expr.callee.name if isinstance(expr.callee, n.Identifier) else ""
    args = [evaluate_expression(a, context) for a in expr.args]
    try:
        from infra.stdlib.functions import call_builtin

        if callee in (
            "env",
            "upper",
            "lower",
            "trim",
            "replace",
            "contains",
            "starts_with",
            "ends_with",
            "split",
            "join",
            "len",
            "min",
            "max",
            "abs",
            "clamp",
            "length",
            "concat",
            "first",
            "last",
            "range",
            "coalesce",
            "if_env",
        ):
            return call_builtin(callee, args)
    except Exception as exc:  # noqa: BLE001 - lenient eval, log for diag
        logger.debug("builtin eval failed (callee=%r): %s", callee, exc)
    if callee == "secret":
        return args[0] if args else None
    if callee == "config":
        return args[0] if args else None
    if callee == "version":
        return args[0] if args else None
    return None


def evaluate_duration(d: n.Duration) -> str:
    """Return a duration as a compact string (e.g. Duration(30,'s') -> '30s')."""
    value = d.value
    if value == int(value):
        return f"{int(value)}{d.unit}"
    return f"{value}{d.unit}"


def evaluate_resource(r: n.ResourceValue, format: str = "kubernetes") -> str:
    """Render a resource value for a given target format."""
    if format == "kubernetes":
        return r.to_kubernetes()
    if format == "docker":
        return str(r.to_bytes())
    return r.to_kubernetes()
