# ruff: noqa: E501
"""Docker Compose backend.

Maps Infra definitions to ``docker-compose.yml`` (version 3.8) plus a generated
``.env.example`` and ``Makefile`` for common local tasks.
"""
# mypy: disable-error-code="no-untyped-def,no-untyped-call,no-any-return,index,attr-defined,type-arg,misc,union-attr,assignment"

from __future__ import annotations

from typing import Any, Dict, Optional

from infra.backends.base import (
    Backend,
    BaseYAMLBackend,
    CompileContext,
    CompileResult,
    evaluate_duration,
    evaluate_expression,
)
from infra.errors.exceptions import InfraCompileError
from infra.parser import ast_nodes as n

_DB_IMAGES = {
    "postgres": ("postgres", {"POSTGRES_DB", "POSTGRES_USER", "POSTGRES_PASSWORD"}),
    "mysql": (
        "mysql",
        {"MYSQL_DATABASE", "MYSQL_USER", "MYSQL_PASSWORD", "MYSQL_ROOT_PASSWORD"},
    ),
    "mongodb": ("mongo", {"MONGO_INITDB_ROOT_USERNAME", "MONGO_INITDB_ROOT_PASSWORD"}),
    "redis": ("redis", {"REDIS_PASSWORD"}),
}
_CACHE_IMAGES = {"redis": "redis", "valkey": "valkey", "memcached": "memcached"}
_QUEUE_IMAGES = {
    "rabbitmq": "rabbitmq:3-management",
    "kafka": "bitnami/kafka",
    "nats": "nats",
}


class DockerComposeBackend(Backend, BaseYAMLBackend):
    name = "compose"
    description = "Docker Compose YAML"
    file_extension = ".yml"
    supports_multi_file = True

    def get_version(self) -> str:
        return "3.8"

    def compile(
        self,
        program: n.Program,
        *,
        cli_vars: Optional[Dict[str, str]] = None,
        **kwargs: Any,
    ) -> CompileResult:
        services: Dict[str, Any] = {}
        networks: Dict[str, Any] = {}
        secrets: Dict[str, Any] = {}
        configs: Dict[str, Any] = {}
        volumes: Dict[str, Any] = {}
        env_vars: Dict[str, str] = {}
        result = CompileResult(metadata={"compose_version": "3.8"})
        ctx = CompileContext.from_program(program, symbol_table=None, cli_vars=cli_vars)

        for stmt in program.statements:
            if isinstance(stmt, n.ServiceDef):
                services[stmt.name] = self._service(stmt, env_vars, ctx)
            elif isinstance(stmt, n.DatabaseDef):
                services[stmt.name] = self._database(stmt, env_vars)
            elif isinstance(stmt, n.CacheDef):
                services[stmt.name] = self._cache(stmt)
            elif isinstance(stmt, n.QueueDef):
                services[stmt.name] = self._queue(stmt)
            elif isinstance(stmt, n.StorageDef):
                if stmt.type == "minio":
                    services[stmt.name] = self._minio(stmt, env_vars)
            elif isinstance(stmt, n.SecretDef):
                for e in stmt.entries:
                    if e.value is not None:
                        env_vars[stmt.name.upper() + "_" + e.name.upper()] = e.value
                secrets[stmt.name] = {"file": f"./{stmt.name}.txt"}
            elif isinstance(stmt, n.ConfigDef):
                for e in stmt.entries:
                    if e.value is not None:
                        env_vars[f"{stmt.name.upper()}_{e.name.upper()}"] = str(
                            _lit(e.value)
                        )
                configs[stmt.name] = {"content": self._config_content(stmt)}
            elif isinstance(stmt, n.NetworkDef):
                networks[stmt.name] = {"driver": "bridge"}

        # Declare any named volumes referenced by services at the top level so
        # Docker Compose actually provisions them.
        for svc in services.values():
            for vol in svc.get("volumes", []) or []:
                if isinstance(vol, str) and ":" in vol:
                    name = vol.split(":", 1)[0]
                    if name and not name.startswith((".", "/", "~", "${")):
                        volumes.setdefault(name, {})
                elif isinstance(vol, dict) and "source" in vol:
                    src = vol["source"]
                    if src and not src.startswith((".", "/", "~", "${")):
                        volumes.setdefault(src, {})

        # Docker Compose v2 ignores a top-level `version:` key (emitting one
        # triggers a deprecation warning), so we deliberately omit it.
        compose: Dict[str, Any] = {}
        if services:
            compose["services"] = services
        if networks:
            compose["networks"] = networks
        if secrets:
            compose["secrets"] = secrets
        if configs:
            compose["configs"] = configs
        if volumes:
            compose["volumes"] = volumes

        result.files["docker-compose.yml"] = (
            "# Generated by Infra Language - DO NOT EDIT\n" + self._to_yaml(compose)
        )
        result.files[".env.example"] = (
            "\n".join(f"{k}={v}" for k, v in sorted(env_vars.items())) + "\n"
        )
        result.files["Makefile"] = self._makefile(services)
        return result

    def compile_service(self, node: n.ServiceDef) -> str:
        env: Dict[str, str] = {}
        return self._to_yaml(self._service(node, env))

    def compile_database(self, node: n.DatabaseDef) -> str:
        env: Dict[str, str] = {}
        return self._to_yaml(self._database(node, env))

    # ------------------------------------------------------------------ #
    def _service(
        self,
        node: n.ServiceDef,
        env_vars: Dict[str, str],
        ctx: Optional[CompileContext] = None,
    ) -> Dict[str, Any]:
        if node.image is None and node.build is None:
            raise InfraCompileError(
                f"Service '{node.name}' needs image or build",
                backend=self.name,
                node=node,
            )
        svc: Dict[str, Any] = {}
        if node.image:
            if isinstance(node.image, str):
                svc["image"] = node.image
            elif ctx is not None:
                svc["image"] = evaluate_expression(node.image, ctx)
            else:
                svc["image"] = str(node.image)
        if node.build:
            b = node.build
            build = {"context": b.context or "."}
            if b.dockerfile:
                build["dockerfile"] = b.dockerfile
            if b.target:
                build["target"] = b.target
            svc["build"] = build
        if node.ports:
            svc["ports"] = [
                f"{p.host or p.target}:{p.target or p.host}" for p in node.ports
            ]
        if node.env:
            svc["environment"] = {e.name: self._env_val(e, ctx) for e in node.env}
            for e in node.env:
                if e.value is not None and _lit(e.value):
                    env_vars[node.name.upper() + "_" + e.name.upper()] = _lit(e.value)
        if node.command:
            svc["command"] = list(node.command)
        if node.volumes:
            svc["volumes"] = [
                f"{v.name}:{v.mount_path or '/data'}" for v in node.volumes
            ]
        depends = _string_list(node.depends)
        if depends:
            svc["depends_on"] = {d: {"condition": "service_healthy"} for d in depends}
        if node.health:
            svc["healthcheck"] = self._healthcheck(node.health)
        if node.replicas and node.replicas > 1:
            svc["deploy"] = {"replicas": int(node.replicas)}
        return svc

    def _env_val(self, e: n.EnvEntry, ctx: Optional[CompileContext] = None) -> str:
        if e.from_env:
            return f"${{{e.from_env}}}"
        if e.from_secret:
            return f"${{{e.from_secret.replace('.', '_')}}}"
        if e.value is not None:
            if isinstance(e.value, n.Literal):
                return _lit(e.value)
            if ctx is not None:
                val = evaluate_expression(e.value, ctx)
                return str(val) if val is not None else ""
        return _lit(e.value) if e.value is not None else ""

    def _database(
        self, node: n.DatabaseDef, env_vars: Dict[str, str]
    ) -> Dict[str, Any]:
        img, _ = _DB_IMAGES.get(node.type, ("postgres", set()))
        version = node.version or ""
        svc: Dict[str, Any] = {"image": f"{img}:{version}" if version else img}
        env: Dict[str, str] = {}
        if node.type == "postgres":
            env.update({"POSTGRES_DB": node.name, "POSTGRES_USER": node.name})
            if node.users:
                env["POSTGRES_PASSWORD"] = node.users[0].password or "change-me"
        elif node.type == "mysql":
            env.update(
                {
                    "MYSQL_DATABASE": node.name,
                    "MYSQL_USER": node.name,
                    "MYSQL_PASSWORD": (
                        node.users[0].password if node.users else "change-me"
                    ),
                    "MYSQL_ROOT_PASSWORD": "root",
                }
            )
        elif node.type == "mongodb":
            if node.users:
                env.update(
                    {
                        "MONGO_INITDB_ROOT_USERNAME": node.users[0].name,
                        "MONGO_INITDB_ROOT_PASSWORD": node.users[0].password
                        or "change-me",
                    }
                )
        svc["environment"] = env
        svc["volumes"] = [f"{node.name}-data:/var/lib/postgresql/data"]
        if node.type == "postgres":
            svc["healthcheck"] = {
                "test": ["CMD", "pg_isready", "-U", node.name],
                "interval": "10s",
                "retries": 5,
            }
        for k, v in env.items():
            env_vars[f"{node.name.upper()}_{k}"] = v
        return svc

    def _cache(self, node: n.CacheDef) -> Dict[str, Any]:
        img = _CACHE_IMAGES.get(node.type, "redis")
        version = node.version or ("7" if node.type in ("redis", "valkey") else "1.6")
        svc: Dict[str, Any] = {"image": f"{img}:{version}"}
        if node.type == "redis" and node.maxmemory:
            svc["command"] = [
                "redis-server",
                "--maxmemory",
                node.maxmemory.to_kubernetes(),
                "--maxmemory-policy",
                node.policy or "allkeys-lru",
            ]
        if node.persistence:
            svc["volumes"] = [f"{node.name}-data:/data"]
        return svc

    def _queue(self, node: n.QueueDef) -> Dict[str, Any]:
        img = _QUEUE_IMAGES.get(node.type, "rabbitmq:3-management")
        svc: Dict[str, Any] = {"image": img}
        if node.users and node.type == "rabbitmq":
            svc["environment"] = {
                "RABBITMQ_DEFAULT_USER": node.users[0].name,
                "RABBITMQ_DEFAULT_PASS": node.users[0].password or "change-me",
            }
        svc["ports"] = ["15672:15672", "5672:5672"]
        svc["volumes"] = [f"{node.name}-data:/var/lib/rabbitmq"]
        return svc

    def _minio(self, node: n.StorageDef, env_vars: Dict[str, str]) -> Dict[str, Any]:
        env = {"MINIO_ROOT_USER": "minioadmin", "MINIO_ROOT_PASSWORD": "minioadmin"}
        env_vars.update(
            {
                f"{node.name.upper()}_USER": "minioadmin",
                f"{node.name.upper()}_PASSWORD": "minioadmin",
            }
        )
        return {
            "image": "minio/minio",
            "command": ["server", "/data"],
            "environment": env,
            "volumes": [f"{node.name}-data:/data"],
            "ports": ["9000:9000"],
        }

    def _healthcheck(self, h: n.HealthSpec) -> Dict[str, Any]:
        hc: Dict[str, Any] = {}
        if h.kind == "http":
            hc["test"] = [
                "CMD",
                "curl",
                "-f",
                f"http://localhost:{h.port or 80}{h.path or '/'}",
            ]
        elif h.kind == "tcp":
            hc["test"] = ["CMD", "nc", "-z", "localhost", str(h.port or 80)]
        if h.interval:
            hc["interval"] = evaluate_duration(h.interval)
        if h.timeout:
            hc["timeout"] = evaluate_duration(h.timeout)
        if h.retries:
            hc["retries"] = h.retries
        return hc

    def _config_content(self, node: n.ConfigDef) -> str:
        lines = []
        for e in node.entries:
            if e.value is not None:
                lines.append(f"{e.name}={_lit(e.value)}")
        return "\n".join(lines) + "\n"

    def _makefile(self, services: Dict[str, Any]) -> str:
        lines = [
            "# Generated by Infra Language - DO NOT EDIT",
            ".PHONY: up down logs ps build shell",
            "up:",
            "\tdocker compose up -d",
            "down:",
            "\tdocker compose down",
            "logs:",
            "\tdocker compose logs -f",
            "ps:",
            "\tdocker compose ps",
            "build:",
            "\tdocker compose build",
            "shell:",
            "\t@echo 'Usage: make shell SERVICE'",
        ]
        first = next(iter(services), "app")
        lines.append(f"shell-{first}:")
        lines.append(f"\tdocker compose exec {first} /bin/sh")
        return "\n".join(lines) + "\n"


def _lit(v: Any) -> str:
    if isinstance(v, n.Literal):
        return str(v.value)
    return str(v)


def _string_list(value):
    items = value.items if isinstance(value, n.List) else (value or ())
    return tuple(_lit(i) for i in items)
