# ruff: noqa: E501
"""GitHub Actions backend.

Maps ``pipeline`` definitions to ``.github/workflows/<name>.yml`` files and
generates a ``.github/dependabot.yml``.
"""
# mypy: disable-error-code="no-untyped-def,no-untyped-call,no-any-return,index,attr-defined,type-arg,misc,union-attr,assignment"

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List

from infra.backends.base import Backend, BaseYAMLBackend, CompileResult
from infra.errors.exceptions import InfraCompileError
from infra.parser import ast_nodes as n

#: Recognized shorthand -> action reference
_ACTIONS = {
    "checkout": ("actions/checkout@v4", {}),
    "docker-login": (
        "docker/login-action@v3",
        {
            "username": "${{ secrets.DOCKER_USERNAME }}",
            "password": "${{ secrets.DOCKER_PASSWORD }}",
        },
    ),
    "docker-build-push": ("docker/build-push-action@v5", {}),
    "upload-artifact": ("actions/upload-artifact@v3", {}),
    "download-artifact": ("actions/download-artifact@v3", {}),
}


class GitHubActionsBackend(Backend, BaseYAMLBackend):
    name = "github"
    description = "GitHub Actions workflows"
    file_extension = ".yml"
    supports_multi_file = True

    def get_version(self) -> str:
        return "v1"

    def compile(self, program: n.Program, *, cli_vars=None, **kwargs) -> CompileResult:
        result = CompileResult(
            metadata={"generated_at": datetime.now(timezone.utc).isoformat()}
        )
        for stmt in program.statements:
            if isinstance(stmt, n.PipelineDef):
                wf = self._workflow(stmt)
                result.files[f"{self._slug(stmt.name)}.yml"] = (
                    f"# Generated by Infra Language - DO NOT EDIT\n"
                    f"# Generated: {datetime.now(timezone.utc).isoformat()}\n"
                    + self._to_yaml(wf)
                )
        result.files["dependabot.yml"] = self._dependabot()
        return result

    def compile_service(self, node: n.ServiceDef) -> str:
        raise InfraCompileError(
            "Services are not supported by the GitHub Actions backend",
            backend=self.name,
            node=node,
        )

    def compile_database(self, node: n.DatabaseDef) -> str:
        raise InfraCompileError(
            "Databases are not supported by the GitHub Actions backend",
            backend=self.name,
            node=node,
        )

    # ------------------------------------------------------------------ #
    def _workflow(self, node: n.PipelineDef) -> Dict[str, Any]:
        wf: Dict[str, Any] = {"name": node.name}
        if node.trigger:
            wf["on"] = self._trigger(node.trigger)
        if node.concurrency:
            wf["concurrency"] = {
                "group": node.concurrency.group,
                "cancel-in-progress": node.concurrency.cancel_in_progress,
            }
        jobs: Dict[str, Any] = {}
        for stage in node.stages:
            jobs[self._slug(stage.name)] = self._job(stage)
        if node.artifacts:
            jobs = self._inject_artifacts(jobs, node)
        wf["jobs"] = jobs
        return wf

    def _trigger(self, t: n.TriggerSpec) -> Dict[str, Any]:
        out: Dict[str, Any] = {}
        push: Dict[str, Any] = {}
        pr: Dict[str, Any] = {}
        if t.branches:
            push["branches"] = list(t.branches)
            pr["branches"] = list(t.branches)
        if t.tags:
            push["tags"] = list(t.tags)
        if t.paths:
            push["paths"] = list(t.paths)
            pr["paths"] = list(t.paths)
        if push:
            out["push"] = push
        if pr:
            out["pull_request"] = pr
        if t.schedule:
            out["schedule"] = [{"cron": t.schedule}]
        if t.manual:
            out["workflow_dispatch"] = {}
        if t.events:
            for ev in t.events:
                out.setdefault(ev, {})
        return out

    def _job(self, stage: n.StageSpec) -> Dict[str, Any]:
        job: Dict[str, Any] = {"name": stage.name}
        if stage.needs:
            job["needs"] = [self._slug(x) for x in stage.needs]
        if stage.condition:
            job["if"] = stage.condition
        if stage.runs_on:
            job["runs-on"] = stage.runs_on
        if stage.timeout:
            job["timeout-minutes"] = int(stage.timeout.to_seconds() // 60)
        if stage.matrix:
            dims = {name: list(vals) for name, vals in stage.matrix.dimensions}
            job["strategy"] = {"matrix": dims}
        if stage.image and not stage.runs_on:
            job["container"] = {"image": stage.image}
        if stage.env:
            job["env"] = dict(stage.env)
        steps: List[Dict[str, Any]] = []
        for step in stage.steps:
            steps.append(self._step(step))
        if steps:
            job["steps"] = steps
        return job

    def _step(self, step: n.StepSpec) -> Dict[str, Any]:
        s: Dict[str, Any] = {"name": step.name}
        if step.uses:
            action, with_args = self._resolve_action(step.uses)
            s["uses"] = action
            if with_args:
                s["with"] = with_args
            if step.with_args:
                s["with"] = {
                    **s.get("with", {}),
                    **{k: _lit(v) for k, v in step.with_args},
                }
        elif step.run:
            s["run"] = step.run
        if step.condition:
            s["if"] = step.condition
        if step.continue_on_error:
            s["continue-on-error"] = True
        if step.timeout:
            s["timeout-minutes"] = int(step.timeout.to_seconds() // 60)
        if step.env:
            s["env"] = dict(step.env)
        return s

    def _resolve_action(self, use: str) -> Any:
        u = use.strip()
        if u in _ACTIONS:
            return _ACTIONS[u]
        if u.startswith("setup-python"):
            version = u.split(" ")[-1]
            return ("actions/setup-python@v4", {"python-version": version})
        if u.startswith("setup-node"):
            version = u.split(" ")[-1]
            return ("actions/setup-node@v4", {"node-version": version})
        if u.startswith("setup-go"):
            version = u.split(" ")[-1]
            return ("actions/setup-go@v5", {"go-version": version})
        if u.startswith("setup-java"):
            version = u.split(" ")[-1]
            return (
                "actions/setup-java@v4",
                {"distribution": "temurin", "java-version": version},
            )
        if u.startswith("setup-python"):
            pass
        if "@" in u:
            return (u, {})
        # assume a plain action name
        return (u, {})

    def _inject_artifacts(
        self, jobs: Dict[str, Any], node: n.PipelineDef
    ) -> Dict[str, Any]:
        # add upload step to the last job that has steps
        last_steps_job = None
        for name, job in jobs.items():
            if job.get("steps"):
                last_steps_job = name
        if last_steps_job is None:
            return jobs
        job = jobs[last_steps_job]
        if node.artifacts and node.artifacts.upload:
            for path in node.artifacts.upload:
                job["steps"].append(
                    {
                        "name": f"Upload artifact {path}",
                        "uses": "actions/upload-artifact@v3",
                        "with": {"name": "artifact", "path": path},
                    }
                )
        return jobs

    def _dependabot(self) -> str:
        conf = {
            "version": 2,
            "updates": [
                {
                    "package-ecosystem": "github-actions",
                    "directory": "/",
                    "schedule": {"interval": "weekly"},
                },
                {
                    "package-ecosystem": "pip",
                    "directory": "/",
                    "schedule": {"interval": "weekly"},
                },
            ],
        }
        return "# Generated by Infra Language - DO NOT EDIT\n" + self._to_yaml(conf)

    @staticmethod
    def _slug(name: str) -> str:
        out = []
        for ch in name:
            if ch.isalnum() or ch == "_":
                out.append(ch)
            elif ch in ("-", " "):
                out.append("_")
        return "".join(out).strip("_") or "job"


def _lit(v: Any) -> str:
    if isinstance(v, n.Literal):
        return str(v.value)
    return str(v)
